import { Sector } from './sector.enum';

/** A company's industry. */
export enum Industry {
  // COMMUNICATION_SERVICES
  DIVERSIFIED_TELECOMMUNICATION_SERVICES = 'DIVERSIFIED_TELECOMMUNICATION_SERVICES',
  ENTERTAINMENT = 'ENTERTAINMENT',
  INTERACTIVE_MEDIA_AND_SERVICES = 'INTERACTIVE_MEDIA_AND_SERVICES',
  MEDIA = 'MEDIA',
  WIRELESS_TELECOMMUNICATION_SERVICES = 'WIRELESS_TELECOMMUNICATION_SERVICES',
  //CONSUMER_DISCRETIONARY
  AUTO_COMPONENTS = 'AUTO_COMPONENTS',
  AUTOMOBILES = 'AUTOMOBILES',
  DISTRIBUTORS = 'DISTRIBUTORS',
  DIVERSIFIED_CONSUMER_SERVICES = 'DIVERSIFIED_CONSUMER_SERVICES',
  HOTELS_RESTAURANTS_LEISURE = 'HOTELS_RESTAURANTS_LEISURE',
  HOUSEHOLD_DURABLES = 'HOUSEHOLD_DURABLES',
  INTERNET_AND_DIRECT_MARKETING_RETAIL = 'INTERNET_AND_DIRECT_MARKETING_RETAIL',
  LEISURE_PRODUCTS = 'LEISURE_PRODUCTS',
  MULTILINE_RETAIL = 'MULTILINE_RETAIL',
  SPECIALTY_RETAIL = 'SPECIALTY_RETAIL',
  TEXTILES_APPAREL_LUXURY_GOODS = 'TEXTILES_APPAREL_LUXURY_GOODS',
  // CONSUMER_STAPLES
  BEVERAGES = 'BEVERAGES',
  FOOD_AND_STAPLES_RETAILING = 'FOOD_AND_STAPLES_RETAILING',
  FOOD_PRODUCTS = 'FOOD_PRODUCTS',
  HOUSEHOLD_PRODUCTS = 'HOUSEHOLD_PRODUCTS',
  PERSONAL_PRODUCTS = 'PERSONAL_PRODUCTS',
  TOBACCO = 'TOBACCO',
  // ENERGY
  ENERGY_EQUIPMENT_AND_SERVICES = 'ENERGY_EQUIPMENT_AND_SERVICES',
  OIL_GAS_CONSUMABLE_FUELS = 'OIL_GAS_CONSUMABLE_FUELS',
  // FINANCIALS
  BANKS = 'BANKS',
  CAPITAL_MARKETS = 'CAPITAL_MARKETS',
  CONSUMER_FINANCE = 'CONSUMER_FINANCE',
  DIVERSIFIED_FINANCIAL_SERVICES = 'DIVERSIFIED_FINANCIAL_SERVICES',
  INSURANCE = 'INSURANCE',
  MORTGAGE_REITS = 'MORTGAGE_REITS',
  THRIFTS_MORTGAGE_FINANCE = 'THRIFTS_MORTGAGE_FINANCE',
  // HEALTHCARE
  BIOTECHNOLOGY = 'BIOTECHNOLOGY',
  HEALTHCARE_EQUIPMENT_AND_SUPPLIES = 'HEALTHCARE_EQUIPMENT_AND_SUPPLIES',
  HEALTHCARE_PROVIDERS_AND_SERVICES = 'HEALTHCARE_PROVIDERS_AND_SERVICES',
  HEALTHCARE_TECHNOLOGY = 'HEALTHCARE_TECHNOLOGY',
  LIFE_SCIENCES_TOOLS_AND_SERVICES = 'LIFE_SCIENCES_TOOLS_AND_SERVICES',
  PHARMACEUTICALS = 'PHARMACEUTICALS',
  // INDUSTRIALS
  AEROSPACE_DEFENSE = 'AEROSPACE_DEFENSE',
  AIR_FREIGHT_AND_LOGISTICS = 'AIR_FREIGHT_AND_LOGISTICS',
  AIRLINES = 'AIRLINES',
  BUILDING_PRODUCTS = 'BUILDING_PRODUCTS',
  COMMERCIAL_SERVICES_AND_SUPPLIES = 'COMMERCIAL_SERVICES_AND_SUPPLIES',
  CONSTRUCTION_AND_ENGINEERING = 'CONSTRUCTION_AND_ENGINEERING',
  ELECTRICAL_EQUIPMENT = 'ELECTRICAL_EQUIPMENT',
  INDUSTRIAL_CONGLOMERATES = 'INDUSTRIAL_CONGLOMERATES',
  MACHINERY = 'MACHINERY',
  MARINE = 'MARINE',
  PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
  ROAD_RAIL = 'ROAD_RAIL',
  TRADING_COMPANIES_AND_DISTRIBUTORS = 'TRADING_COMPANIES_AND_DISTRIBUTORS',
  TRANSPORTATION_INFRASTRUCTURE = 'TRANSPORTATION_INFRASTRUCTURE',
  // INFORMATION_TECHNOLOGY
  COMMUNICATIONS_EQUIPMENT = 'COMMUNICATIONS_EQUIPMENT',
  ELECTRONIC_EQUIPMENT_INSTRUMENTS_COMPONENTS = 'ELECTRONIC_EQUIPMENT_INSTRUMENTS_COMPONENTS',
  IT_SERVICES = 'IT_SERVICES',
  SEMICONDUCTORS_AND_SEMICONDUCTOR_EQUIPMENT = 'SEMICONDUCTORS_AND_SEMICONDUCTOR_EQUIPMENT',
  SOFTWARE = 'SOFTWARE',
  TECHNOLOGY_HARDWARE_STORAGE_AND_PERIPHERALS = 'TECHNOLOGY_HARDWARE_STORAGE_AND_PERIPHERALS',
  // MATERIALS
  CHEMICALS = 'CHEMICALS',
  CONSTRUCTION_MATERIALS = 'CONSTRUCTION_MATERIALS',
  CONTAINERS_AND_PACKAGING = 'CONTAINERS_AND_PACKAGING',
  METALS_AND_MINING = 'METALS_AND_MINING',
  PAPER_AND_FOREST_PRODUCTS = 'PAPER_AND_FOREST_PRODUCTS',
  // REAL_ESTATE
  EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS = 'EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS',
  REAL_ESTATE_MANAGEMENT_AND_DEVELOPMENT = 'REAL_ESTATE_MANAGEMENT_AND_DEVELOPMENT',
  // UTILITIES
  ELECTRIC_UTILITIES = 'ELECTRIC_UTILITIES',
  GAS_UTILITIES = 'GAS_UTILITIES',
  INDEPENDENT_POWER_AND_RENEWABLE_ELECTRICITY_PRODUCERS = 'INDEPENDENT_POWER_AND_RENEWABLE_ELECTRICITY_PRODUCERS',
  MULTI_UTILITIES = 'MULTI_UTILITIES',
  WATER_UTILITIES = 'WATER_UTILITIES',
}

export const industries: Map<Sector, Industry[]> = new Map([
  [
    Sector.COMMUNICATION_SERVICES,
    [
      Industry.DIVERSIFIED_TELECOMMUNICATION_SERVICES,
      Industry.ENTERTAINMENT,
      Industry.INTERACTIVE_MEDIA_AND_SERVICES,
      Industry.MEDIA,
      Industry.WIRELESS_TELECOMMUNICATION_SERVICES,
    ],
  ],

  [
    Sector.CONSUMER_DISCRETIONARY,
    [
      Industry.AUTO_COMPONENTS,
      Industry.AUTOMOBILES,
      Industry.DISTRIBUTORS,
      Industry.DIVERSIFIED_CONSUMER_SERVICES,
      Industry.HOTELS_RESTAURANTS_LEISURE,
      Industry.HOUSEHOLD_DURABLES,
      Industry.INTERNET_AND_DIRECT_MARKETING_RETAIL,
      Industry.LEISURE_PRODUCTS,
      Industry.MULTILINE_RETAIL,
      Industry.SPECIALTY_RETAIL,
      Industry.TEXTILES_APPAREL_LUXURY_GOODS,
    ],
  ],

  [
    Sector.CONSUMER_STAPLES,
    [
      Industry.BEVERAGES,
      Industry.FOOD_AND_STAPLES_RETAILING,
      Industry.FOOD_PRODUCTS,
      Industry.HOUSEHOLD_PRODUCTS,
      Industry.PERSONAL_PRODUCTS,
      Industry.TOBACCO,
    ],
  ],

  [
    Sector.ENERGY,
    [Industry.ENERGY_EQUIPMENT_AND_SERVICES, Industry.OIL_GAS_CONSUMABLE_FUELS],
  ],

  [
    Sector.FINANCIALS,
    [
      Industry.BANKS,
      Industry.CAPITAL_MARKETS,
      Industry.CONSUMER_FINANCE,
      Industry.DIVERSIFIED_FINANCIAL_SERVICES,
      Industry.INSURANCE,
      Industry.MORTGAGE_REITS,
      Industry.THRIFTS_MORTGAGE_FINANCE,
    ],
  ],

  [
    Sector.HEALTHCARE,
    [
      Industry.BIOTECHNOLOGY,
      Industry.HEALTHCARE_EQUIPMENT_AND_SUPPLIES,
      Industry.HEALTHCARE_PROVIDERS_AND_SERVICES,
      Industry.HEALTHCARE_TECHNOLOGY,
      Industry.LIFE_SCIENCES_TOOLS_AND_SERVICES,
      Industry.PHARMACEUTICALS,
    ],
  ],

  [
    Sector.INDUSTRIALS,
    [
      Industry.AEROSPACE_DEFENSE,
      Industry.AIR_FREIGHT_AND_LOGISTICS,
      Industry.AIRLINES,
      Industry.BUILDING_PRODUCTS,
      Industry.COMMERCIAL_SERVICES_AND_SUPPLIES,
      Industry.CONSTRUCTION_AND_ENGINEERING,
      Industry.ELECTRICAL_EQUIPMENT,
      Industry.INDUSTRIAL_CONGLOMERATES,
      Industry.MACHINERY,
      Industry.MARINE,
      Industry.PROFESSIONAL_SERVICES,
      Industry.ROAD_RAIL,
      Industry.TRADING_COMPANIES_AND_DISTRIBUTORS,
      Industry.TRANSPORTATION_INFRASTRUCTURE,
    ],
  ],

  [
    Sector.INFORMATION_TECHNOLOGY,
    [
      Industry.COMMUNICATIONS_EQUIPMENT,
      Industry.ELECTRONIC_EQUIPMENT_INSTRUMENTS_COMPONENTS,
      Industry.IT_SERVICES,
      Industry.SEMICONDUCTORS_AND_SEMICONDUCTOR_EQUIPMENT,
      Industry.SOFTWARE,
      Industry.TECHNOLOGY_HARDWARE_STORAGE_AND_PERIPHERALS,
    ],
  ],

  [
    Sector.MATERIALS,
    [
      Industry.CHEMICALS,
      Industry.CONSTRUCTION_MATERIALS,
      Industry.CONTAINERS_AND_PACKAGING,
      Industry.METALS_AND_MINING,
      Industry.PAPER_AND_FOREST_PRODUCTS,
    ],
  ],

  [
    Sector.REAL_ESTATE,
    [
      Industry.EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS,
      Industry.REAL_ESTATE_MANAGEMENT_AND_DEVELOPMENT,
    ],
  ],

  [
    Sector.UTILITIES,
    [
      Industry.ELECTRIC_UTILITIES,
      Industry.GAS_UTILITIES,
      Industry.INDEPENDENT_POWER_AND_RENEWABLE_ELECTRICITY_PRODUCERS,
      Industry.MULTI_UTILITIES,
      Industry.WATER_UTILITIES,
    ],
  ],
]);
