/** A company's sector. */
export enum Sector {
  COMMUNICATION_SERVICES = 'COMMUNICATION_SERVICES',
  CONSUMER_DISCRETIONARY = 'CONSUMER_DISCRETIONARY',
  CONSUMER_STAPLES = 'CONSUMER_STAPLES',
  ENERGY = 'ENERGY',
  FINANCIALS = 'FINANCIALS',
  HEALTHCARE = 'HEALTHCARE',
  INDUSTRIALS = 'INDUSTRIALS',
  INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY',
  MATERIALS = 'MATERIALS',
  REAL_ESTATE = 'REAL_ESTATE',
  UTILITIES = 'UTILITIES',
}

export const sectors: Sector[] = [
  Sector.COMMUNICATION_SERVICES,
  Sector.CONSUMER_DISCRETIONARY,
  Sector.CONSUMER_STAPLES,
  Sector.ENERGY,
  Sector.FINANCIALS,
  Sector.HEALTHCARE,
  Sector.INDUSTRIALS,
  Sector.INFORMATION_TECHNOLOGY,
  Sector.MATERIALS,
  Sector.REAL_ESTATE,
  Sector.UTILITIES,
];
