/** A company's sector. */
export enum Sector {
  COMMUNICATION_SERVICES,
  CONSUMER_DISCRETIONARY,
  CONSUMER_STAPLES,
  ENERGY,
  FINANCIALS,
  HEALTHCARE,
  INDUSTRIALS,
  INFORMATION_TECHNOLOGY,
  MATERIALS,
  REAL_ESTATE,
  UTILITIES,
}
