import { Timescale } from '../enums/timescale.enum';
import { AnalysisResults } from '../models/analysis-results.model';
import { CrossingType } from '../models/crossing-type.model';

/** Helper functions for anything price related. */
export class PriceUtils {
  /** What score this price can be given in comparison to the other given parameters. */
  public static getPriceAppreciation(
    price: number,
    nextHigh: number,
    prevHigh: number,
    low: number
  ): number {
    let score = 0;
    if (price > nextHigh || price > prevHigh) {
      score = -1;
    } else if (price < nextHigh) {
      const tranche = (nextHigh - low) / 5;
      if (price <= low + tranche) {
        score = 5;
      } else if (price <= low + tranche * 2) {
        score = 4;
      } else if (price <= low + tranche * 3) {
        score = 3;
      } else if (price <= low + tranche * 4) {
        score = 2;
      } else {
        score = 1;
      }
    }
    return score;
  }

  /** What score this growth rate can be given? */
  public static getGrowthScore(growth: number): number {
    let score = 0;
    if (growth < 0) {
      score = -1;
    } else if (growth > 1) {
      score = 5;
    } else if (growth > 0.75) {
      score = 4;
    } else if (growth > 0.5) {
      score = 3;
    } else if (growth > 0.25) {
      score = 2;
    } else {
      score = 1;
    }
    return score;
  }

  /** Returns a timestamp formatted to display, with more or less infos depending on the timescale. */
  public static getPriceTimestamp(timestamp: Date, timescale: Timescale) {
    return timescale === Timescale.FH
      ? timestamp.toLocaleDateString('en-UK', {
          hour: '2-digit',
          minute: '2-digit',
          day: '2-digit',
          month: '2-digit',
          year: '2-digit',
        })
      : timestamp.toLocaleDateString('en-UK', {
          day: '2-digit',
          month: '2-digit',
          year: '2-digit',
        });
  }

  /** Returns a string usable in html to display the given analysis results with proper formatting. */
  public static getAnalysisResultsWithClass(results: AnalysisResults): string {
    return (
      '<span class="' +
      PriceUtils.getPriceClass(
        PriceUtils.getGrowthScore(results.gainsAfterTwoYears)
      ) +
      '">' +
      (results.gainsAfterTwoYears >= 0 ? '+' : '') +
      results.gainsAfterTwoYears * 100 +
      '%</span><br><span class="smaller">avg: ' +
      results.costAverage +
      '<br>used: ' +
      Math.round(results.usedCapital * 100) +
      '%</span>'
    );
  }

  /** Returns the css class corresponding to the given score. */
  public static getPriceClass(score: number): string {
    switch (score) {
      case -1:
        return 'neg-price';
      case 0:
        return 'neutral-price';
      case 1:
        return 'pos-one-price';
      case 2:
        return 'pos-two-price';
      case 3:
        return 'pos-three-price';
      case 4:
        return 'pos-four-price';
      case 5:
        return 'pos-five-price';
      default:
        return '';
    }
  }

  /** Returns a string usable in html to display the crossings column headers with pretty colors. */
  public static getCrossingWithClass(type: CrossingType): string {
    return (
      PriceUtils.getMAClass(type.firstMA, PriceUtils.getMAScore(type.firstMA)) +
      '↗️' +
      PriceUtils.getMAClass(type.intoMA, PriceUtils.getMAScore(type.intoMA))
    );
  }

  /** Returns a "score" usable to return a css class to a MA. */
  public static getMAScore(ma: number): number {
    return ma <= 20
      ? 13
      : ma <= 40
      ? 30
      : ma <= 75
      ? 50
      : ma <= 125
      ? 100
      : ma <= 175
      ? 150
      : 200;
  }

  /** Returns a css class for a given MA using a score that can be generated by PriceUtils.getMAScore(). */
  public static getMAClass(ma: number, score: number) {
    switch (score) {
      case 13:
        return '<span class="cros-thirteen">' + ma + '</span>';
      case 30:
        return '<span class="cros-thirty">' + ma + '</span>';
      case 50:
        return '<span class="cros-fifty">' + ma + '</span>';
      case 100:
        return '<span class="cros-hundred">' + ma + '</span>';
      case 150:
        return '<span class="cros-hundred-and-fifty">' + ma + '</span>';
      case 200:
        return '<span class="cros-two-hundred">' + ma + '</span>';
      default:
        return '';
    }
  }
}
